// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login with username and password through Keycloak",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reports/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get daily ticket SLA report by date. If date is not provided, today will be used.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Get daily report",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2026-05-05",
                        "description": "Report date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get daily report successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid date format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Report not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ticket-events/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Import ticket events in batch using worker pool",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-events"
                ],
                "summary": "Import ticket events",
                "parameters": [
                    {
                        "description": "Import ticket events request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tickets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get tickets with filters and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "List tickets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by ticket status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by priority",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by requestor ID",
                        "name": "requestor_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by assignee ID",
                        "name": "assignee_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get tickets successfully",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-support-ticket_com_internal_dto_common_PaginatedResult-support-ticket_com_internal_model_Ticket"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new support ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "Create ticket",
                "parameters": [
                    {
                        "description": "Create ticket request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_request.CreateTicketReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ticket created successfully",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-support-ticket_com_internal_model_Ticket"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or invalid priority",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    }
                }
            }
        },
        "/tickets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get ticket detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "Get ticket detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get ticket successfully",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-support-ticket_com_internal_model_Ticket"
                        }
                    },
                    "400": {
                        "description": "Invalid ticket ID",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    }
                }
            }
        },
        "/tickets/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update status of a ticket by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "Update ticket status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update status request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_request.UpdateStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket status updated successfully",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or invalid status transition",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/support-ticket_com_internal_dto_common.APIResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "support-ticket_com_internal_dto_common.APIResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "support-ticket_com_internal_dto_common.APIResponse-support-ticket_com_internal_dto_common_PaginatedResult-support-ticket_com_internal_model_Ticket": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/support-ticket_com_internal_dto_common.PaginatedResult-support-ticket_com_internal_model_Ticket"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "support-ticket_com_internal_dto_common.APIResponse-support-ticket_com_internal_model_Ticket": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.Ticket"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "support-ticket_com_internal_dto_common.PaginatedResult-support-ticket_com_internal_model_Ticket": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/support-ticket_com_internal_model.Ticket"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "support-ticket_com_internal_dto_request.CreateTicketReq": {
            "type": "object",
            "required": [
                "priority",
                "sla_due_at",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 5000
                },
                "priority": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.Priority"
                },
                "sla_due_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 5
                }
            }
        },
        "support-ticket_com_internal_dto_request.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "support-ticket_com_internal_dto_request.UpdateStatusReq": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "note": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.TicketStatus"
                }
            }
        },
        "support-ticket_com_internal_model.Priority": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high"
            ],
            "x-enum-varnames": [
                "PriorityLow",
                "PriorityMedium",
                "PriorityHigh"
            ]
        },
        "support-ticket_com_internal_model.Ticket": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "string"
                },
                "cancelled_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "events": {
                    "description": "TODO:Relations",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/support-ticket_com_internal_model.TicketEvent"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "priority": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.Priority"
                },
                "requestor_id": {
                    "type": "string"
                },
                "resolved_at": {
                    "type": "string"
                },
                "sla_due_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.TicketStatus"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "support-ticket_com_internal_model.TicketEvent": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "event_id": {
                    "type": "integer"
                },
                "from_status": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.TicketStatus"
                },
                "note": {
                    "type": "string"
                },
                "ticket_id": {
                    "type": "integer"
                },
                "to_status": {
                    "$ref": "#/definitions/support-ticket_com_internal_model.TicketStatus"
                }
            }
        },
        "support-ticket_com_internal_model.TicketStatus": {
            "type": "string",
            "enum": [
                "new",
                "assigned",
                "in_progress",
                "resolved",
                "closed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "StatusNew",
                "StatusAssigned",
                "StatusInProgress",
                "StatusResolved",
                "StatusClosed",
                "StatusCancelled"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Support Ticket SLA Processing System API",
	Description:      "REST API for support ticket SLA processing system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
