// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login with username and password through Keycloak",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "password",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successfully",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.LoginSuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.BadRequestResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UnauthorizedResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.InternalServerErrorResponseDoc"
                        }
                    },
                    "503": {
                        "description": "Authentication provider unavailable",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.ServiceUnavailableResponseDoc"
                        }
                    }
                }
            }
        },
        "/reports/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get daily ticket report by date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Get daily report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get daily report successfully",
                        "schema": {
                            "$ref": "#/definitions/common.SuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid date format",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Report not found",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/ticket-events/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Import ticket events in batch from a CSV or JSON file. The file must be uploaded using the ` + "`" + `file` + "`" + ` field.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket Events"
                ],
                "summary": "Import ticket events",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV or JSON file to import",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Import ticket events successfully",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.ImportTicketEventsSuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid import input",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.BadRequestResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UnauthorizedResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.InternalServerErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/tickets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of tickets with optional filters and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "List tickets",
                "parameters": [
                    {
                        "enum": [
                            "new",
                            "assigned",
                            "in_progress",
                            "resolved",
                            "closed",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "Filter by ticket status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "low",
                            "medium",
                            "high"
                        ],
                        "type": "string",
                        "description": "Filter by ticket priority",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by assignee ID",
                        "name": "assignee_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get tickets successfully",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.ListTicketsSuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.BadRequestResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UnauthorizedResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.InternalServerErrorResponseDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new support ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "Create ticket",
                "parameters": [
                    {
                        "description": "Create ticket request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateTicketReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ticket created successfully",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.CreateTicketSuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.BadRequestResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UnauthorizedResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.InternalServerErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/tickets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get ticket detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "Get ticket detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get ticket successfully",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.GetTicketDetailSuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid ticket ID",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.ErrorResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UnauthorizedResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.TicketNotFoundResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.InternalServerErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/tickets/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update status of a ticket by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickets"
                ],
                "summary": "Update ticket status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update status request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket status updated successfully",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UpdateTicketStatusSuccessResponseDoc"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or invalid status transition",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.BadRequestResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.UnauthorizedResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.ForbiddenResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.TicketNotFoundResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/swagger_response.InternalServerErrorResponseDoc"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ErrorDetailDoc": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "field_name"
                },
                "message": {
                    "type": "string",
                    "example": "validation error message"
                }
            }
        },
        "common.ErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERROR_CODE"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.ErrorDetailDoc"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "error message"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "common.ErrorResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/common.ErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "common.SuccessResponseDoc": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "domain.Priority": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high"
            ],
            "x-enum-varnames": [
                "PriorityLow",
                "PriorityMedium",
                "PriorityHigh"
            ]
        },
        "domain.TicketStatus": {
            "type": "string",
            "enum": [
                "new",
                "assigned",
                "in_progress",
                "resolved",
                "closed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "StatusNew",
                "StatusAssigned",
                "StatusInProgress",
                "StatusResolved",
                "StatusClosed",
                "StatusCancelled"
            ]
        },
        "request.CreateTicketReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/domain.Priority"
                },
                "sla_due_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "request.UpdateStatusReq": {
            "type": "object",
            "properties": {
                "note": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.TicketStatus"
                }
            }
        },
        "swagger_response.BadRequestErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_REQUEST_BODY"
                },
                "message": {
                    "type": "string",
                    "example": "invalid request body"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "swagger_response.BadRequestResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.BadRequestErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.CreateTicketSuccessResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger_response.TicketDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "swagger_response.ErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERROR_CODE"
                },
                "message": {
                    "type": "string",
                    "example": "error message"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "swagger_response.ErrorResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.ErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.ForbiddenErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "FORBIDDEN"
                },
                "message": {
                    "type": "string",
                    "example": "you do not have permission to access this resource"
                },
                "status": {
                    "type": "integer",
                    "example": 403
                }
            }
        },
        "swagger_response.ForbiddenResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.ForbiddenErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.GetTicketDetailSuccessResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger_response.TicketEventDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "swagger_response.ImportTicketEventsSuccessResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger_response.TicketEventImportResultDoc"
                },
                "message": {
                    "type": "string",
                    "example": "import completed"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "swagger_response.InternalServerErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INTERNAL_SERVER_ERROR"
                },
                "message": {
                    "type": "string",
                    "example": "internal server error"
                },
                "status": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "swagger_response.InternalServerErrorResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.InternalServerErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.ListTicketsDataDoc": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger_response.TicketEventDoc"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 10
                },
                "total_pages": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "swagger_response.ListTicketsSuccessResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger_response.ListTicketsDataDoc"
                },
                "message": {
                    "type": "string",
                    "example": "Get tickets successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "swagger_response.LoginDataDoc": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIsInR5cCI..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 300
                },
                "refresh_expires_in": {
                    "type": "integer",
                    "example": 1800
                },
                "scope": {
                    "type": "string",
                    "example": "profile email"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "swagger_response.LoginSuccessResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger_response.LoginDataDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "swagger_response.ServiceUnavailableErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "AUTH_PROVIDER_UNAVAILABLE"
                },
                "message": {
                    "type": "string",
                    "example": "authentication provider is unavailable"
                },
                "status": {
                    "type": "integer",
                    "example": 503
                }
            }
        },
        "swagger_response.ServiceUnavailableResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.ServiceUnavailableErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.TicketDoc": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "string",
                    "example": "9ee00625-0436-4f11-8bb1-b9e4f3f7bf88"
                },
                "cancelled_at": {
                    "type": "string",
                    "example": ""
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-15T15:19:55.169302+07:00"
                },
                "description": {
                    "type": "string",
                    "example": "User cannot access internal support system"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "priority": {
                    "type": "string",
                    "example": "low"
                },
                "requestor_id": {
                    "type": "string",
                    "example": "0a5389df-ba3a-4494-a095-126d05c7c2e7"
                },
                "resolved_at": {
                    "type": "string",
                    "example": ""
                },
                "sla_due_at": {
                    "type": "string",
                    "example": "2026-05-17T15:19:55.169302+07:00"
                },
                "status": {
                    "type": "string",
                    "example": "assigned"
                },
                "title": {
                    "type": "string",
                    "example": "Cannot access internal system"
                }
            }
        },
        "swagger_response.TicketEventDoc": {
            "type": "object",
            "properties": {
                "assignee_id": {
                    "type": "string",
                    "example": "9ee00625-0436-4f11-8bb1-b9e4f3f7bf88"
                },
                "cancelled_at": {
                    "type": "string",
                    "example": ""
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-15T15:19:55.169302+07:00"
                },
                "description": {
                    "type": "string",
                    "example": "User cannot access internal support system"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger_response.TicketEventDoc"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "priority": {
                    "type": "string",
                    "example": "low"
                },
                "requestor_id": {
                    "type": "string",
                    "example": "0a5389df-ba3a-4494-a095-126d05c7c2e7"
                },
                "resolved_at": {
                    "type": "string",
                    "example": ""
                },
                "sla_due_at": {
                    "type": "string",
                    "example": "2026-05-17T15:19:55.169302+07:00"
                },
                "status": {
                    "type": "string",
                    "example": "assigned"
                },
                "title": {
                    "type": "string",
                    "example": "Cannot access internal system"
                }
            }
        },
        "swagger_response.TicketEventImportResultDoc": {
            "type": "object",
            "properties": {
                "accepted_count": {
                    "type": "integer",
                    "example": 95
                },
                "duplicate_count": {
                    "type": "integer",
                    "example": 2
                },
                "rejected_count": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "swagger_response.TicketNotFoundErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "TICKET_NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "ticket not found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "swagger_response.TicketNotFoundResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.TicketNotFoundErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.UnauthorizedErrorDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "UNAUTHORIZED"
                },
                "message": {
                    "type": "string",
                    "example": "authorization header is required"
                },
                "status": {
                    "type": "integer",
                    "example": 401
                }
            }
        },
        "swagger_response.UnauthorizedResponseDoc": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/swagger_response.UnauthorizedErrorDoc"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "swagger_response.UpdateTicketStatusSuccessResponseDoc": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "ticket status updated successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Support Ticket SLA Processing System API",
	Description:      "REST API for support ticket SLA processing system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
